"""Generates the systemd unit + udev rule that install real unattended
auto-sync-on-connect (see services/sync-orchestrator/README.md's
"Automation (M9)" section) -- filled in with this install's real paths,
written to state_root/generated/ (a location this process can already
write to), and handed back with the exact sudo commands to copy them
into place. Never executes anything privileged itself -- see
web-gui-backend/README.md's Security posture section, which already
commits to this."""

from __future__ import annotations

from pathlib import Path

from fastapi import APIRouter, Request

from web_gui_backend.atomic import write_text_atomic
from web_gui_backend.device import _default_sync_orchestrator_dir

router = APIRouter()

_SYSTEMD_UNIT_INSTALL_PATH = Path("/etc/systemd/system/music-stack-auto-sync.service")
_UDEV_RULE_INSTALL_PATH = Path("/etc/udev/rules.d/99-ipod-music-stack.rules")

_UDEV_RULE_TEMPLATE = """\
# Triggers music-stack-auto-sync.service whenever an iPod Video (5th/5.5th
# gen) enumerates on the USB bus -- idVendor/idProduct confirmed live
# against a real device. Generated by the web GUI's auto-sync setup card.
#
# KNOWN LIMITATION: 05ac/1209 is only confirmed for a 5th/5.5th generation
# iPod Video. If your device is a different generation, connect it and run
# `lsusb` to find its real idVendor/idProduct, then edit the ATTR lines
# below before installing -- nothing in this project derives that value
# for any other generation yet.
#
# TAG+="systemd" (not RUN+=) is deliberate: a RUN+= script runs inside
# udev's own per-device cgroup and can be killed once udev considers that
# device's event handling finished, even if detached -- confirmed live.
# TAG+="systemd" hands the device off to systemd instead, immune to
# udev's own process/cgroup lifecycle. See services/sync-orchestrator/
# README.md's "Automation (M9)" section for the full story.
ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="05ac", ATTR{idProduct}=="1209", \\
    TAG+="systemd", ENV{SYSTEMD_WANTS}="music-stack-auto-sync.service"
"""

_SYSTEMD_UNIT_TEMPLATE = """\
[Unit]
Description=music-stack: sync a connected iPod to its matching profile
# Started on-demand by 99-ipod-music-stack.rules via
# TAG+="systemd"/ENV{{SYSTEMD_WANTS}} -- not enabled/started at boot.
# Generated by the web GUI's auto-sync setup card, filled in with this
# install's real paths.

[Service]
Type=oneshot
Environment=PYTHONUNBUFFERED=1
ExecStart={sync_orchestrator_bin} auto-sync --config-root {config_root} --library-root {library_root} --state-root {state_root}
StandardOutput=append:{log_path}
StandardError=append:{log_path}
# Runs as root: needed for mount_candidate_devices()'s `udisksctl mount`
# to work reliably without an active graphical session/polkit prompt.
User=root
"""


@router.get("/api/auto-sync/setup")
def get_auto_sync_setup(request: Request) -> dict:
    # systemd has no notion of "this process's cwd" -- a oneshot unit
    # with no WorkingDirectory= starts at "/", so every path baked into
    # ExecStart must be absolute regardless of whether this backend
    # itself was started with a relative --config-root (the documented,
    # common case: `uv run web-gui-backend --config-root config`).
    #
    # host_config_root/host_library_root/host_state_root/
    # host_sync_orchestrator_dir (app.py) override this process's own
    # view when set -- required when this process is itself
    # containerized, since its own config_root/etc. are then a
    # container-internal bind-mount target (e.g. /config), not a path
    # meaning anything to the systemd unit below, which always runs on
    # the bare host. Confirmed live: a real containerized deploy's
    # generated unit tried to exec /app/services/sync-orchestrator/
    # .venv/bin/sync-orchestrator -- a path that only exists inside the
    # container -- and failed on every single trigger since the day it
    # was installed. See notes.md's 2026-09-29 entry.
    #
    # Deliberately NOT .resolve()d when they come from a host_* override:
    # this process's own filesystem view (inside a container) has no
    # idea whether a host path exists, has symlinks, etc. -- resolving
    # it here could silently normalize it against the wrong filesystem.
    # The operator is expected to give an already-absolute real path;
    # this process's own paths (the non-override branch) still get
    # resolved exactly as before, since those genuinely are paths on
    # its own filesystem.
    state = request.app.state
    config_root: Path = state.host_config_root or state.config_root.resolve()
    library_root: Path = state.host_library_root or state.library_root.resolve()
    state_root: Path = state.host_state_root or state.state_root.resolve()
    sync_orchestrator_dir = state.host_sync_orchestrator_dir or Path(
        state.sync_orchestrator_dir or _default_sync_orchestrator_dir()
    ).resolve()
    sync_orchestrator_bin = sync_orchestrator_dir / ".venv" / "bin" / "sync-orchestrator"

    systemd_unit = _SYSTEMD_UNIT_TEMPLATE.format(
        sync_orchestrator_bin=sync_orchestrator_bin,
        config_root=config_root,
        library_root=library_root,
        state_root=state_root,
        log_path=state_root / "auto-sync.log",
    )

    # Deliberately NOT the same `state_root` used above: that one is
    # host_state_root when set, i.e. a path meaningful to the *systemd
    # unit* (which always runs on bare metal). This process itself, when
    # containerized, can only actually write through its OWN filesystem
    # view (state.state_root, e.g. /data/state) -- writing through
    # host_state_root's path string (e.g. /mnt/storage/vcpod/state) from
    # inside the container silently lands in a phantom directory in the
    # container's own writable layer, never reaching the real bind-mounted
    # host path, since nothing maps that exact string to anything inside
    # the container. Confirmed live: every previous call "succeeded" and
    # returned fresh content, but the real file on the host's disk (what
    # the sudo cp install_commands below actually copy from) silently
    # never changed. See notes.md's 2026-09-29 entry (second one, same
    # day as the original host-path fix -- this bug was introduced by
    # that very fix).
    local_generated_dir = state.state_root.resolve() / "generated"
    local_systemd_unit_path = local_generated_dir / "music-stack-auto-sync.service"
    local_udev_rule_path = local_generated_dir / "99-ipod-music-stack.rules"
    write_text_atomic(systemd_unit, local_systemd_unit_path)
    write_text_atomic(_UDEV_RULE_TEMPLATE, local_udev_rule_path)

    # install_commands, by contrast, are shown to a human running `sudo
    # cp` on the bare host -- those need the host-visible path to the
    # same files, i.e. state_root (the host_state_root-aware one), not
    # state.state_root.
    generated_dir = state_root / "generated"
    systemd_unit_path = generated_dir / "music-stack-auto-sync.service"
    udev_rule_path = generated_dir / "99-ipod-music-stack.rules"

    return {
        "systemd_unit": systemd_unit,
        "udev_rule": _UDEV_RULE_TEMPLATE,
        "install_commands": [
            f"sudo cp {systemd_unit_path} {_SYSTEMD_UNIT_INSTALL_PATH}",
            f"sudo cp {udev_rule_path} {_UDEV_RULE_INSTALL_PATH}",
            "sudo systemctl daemon-reload",
            "sudo udevadm control --reload-rules",
        ],
        "status": {
            "systemd_installed": _SYSTEMD_UNIT_INSTALL_PATH.is_file(),
            "udev_rule_installed": _UDEV_RULE_INSTALL_PATH.is_file(),
        },
    }
