"""Generates the systemd unit + udev rule that install real unattended
auto-sync-on-connect (see services/sync-orchestrator/README.md's
"Automation (M9)" section) -- filled in with this install's real paths,
written to state_root/generated/ (a location this process can already
write to), and handed back with the exact sudo commands to copy them
into place. Never executes anything privileged itself -- see
web-gui-backend/README.md's Security posture section, which already
commits to this."""

from __future__ import annotations

from pathlib import Path

from fastapi import APIRouter, Request

from web_gui_backend.atomic import write_text_atomic
from web_gui_backend.device import _default_sync_orchestrator_dir

router = APIRouter()

_SYSTEMD_UNIT_INSTALL_PATH = Path("/etc/systemd/system/music-stack-auto-sync.service")
_UDEV_RULE_INSTALL_PATH = Path("/etc/udev/rules.d/99-ipod-music-stack.rules")

_UDEV_RULE_TEMPLATE = """\
# Triggers music-stack-auto-sync.service whenever an iPod Video (5th/5.5th
# gen) enumerates on the USB bus -- idVendor/idProduct confirmed live
# against a real device. Generated by the web GUI's auto-sync setup card.
#
# KNOWN LIMITATION: 05ac/1209 is only confirmed for a 5th/5.5th generation
# iPod Video. If your device is a different generation, connect it and run
# `lsusb` to find its real idVendor/idProduct, then edit the ATTR lines
# below before installing -- nothing in this project derives that value
# for any other generation yet.
#
# TAG+="systemd" (not RUN+=) is deliberate: a RUN+= script runs inside
# udev's own per-device cgroup and can be killed once udev considers that
# device's event handling finished, even if detached -- confirmed live.
# TAG+="systemd" hands the device off to systemd instead, immune to
# udev's own process/cgroup lifecycle. See services/sync-orchestrator/
# README.md's "Automation (M9)" section for the full story.
ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="05ac", ATTR{idProduct}=="1209", \\
    TAG+="systemd", ENV{SYSTEMD_WANTS}="music-stack-auto-sync.service"
"""

_SYSTEMD_UNIT_TEMPLATE = """\
[Unit]
Description=music-stack: sync a connected iPod to its matching profile
# Started on-demand by 99-ipod-music-stack.rules via
# TAG+="systemd"/ENV{{SYSTEMD_WANTS}} -- not enabled/started at boot.
# Generated by the web GUI's auto-sync setup card, filled in with this
# install's real paths.

[Service]
Type=oneshot
Environment=PYTHONUNBUFFERED=1
ExecStart={sync_orchestrator_bin} auto-sync --config-root {config_root} --library-root {library_root} --state-root {state_root}
StandardOutput=append:{log_path}
StandardError=append:{log_path}
# Runs as root: needed for mount_candidate_devices()'s `udisksctl mount`
# to work reliably without an active graphical session/polkit prompt.
User=root
"""


@router.get("/api/auto-sync/setup")
def get_auto_sync_setup(request: Request) -> dict:
    # systemd has no notion of "this process's cwd" -- a oneshot unit
    # with no WorkingDirectory= starts at "/", so every path baked into
    # ExecStart must be absolute regardless of whether this backend
    # itself was started with a relative --config-root (the documented,
    # common case: `uv run web-gui-backend --config-root config`).
    config_root: Path = request.app.state.config_root.resolve()
    library_root: Path = request.app.state.library_root.resolve()
    state_root: Path = request.app.state.state_root.resolve()
    sync_orchestrator_dir = Path(
        request.app.state.sync_orchestrator_dir or _default_sync_orchestrator_dir()
    ).resolve()
    sync_orchestrator_bin = sync_orchestrator_dir / ".venv" / "bin" / "sync-orchestrator"

    systemd_unit = _SYSTEMD_UNIT_TEMPLATE.format(
        sync_orchestrator_bin=sync_orchestrator_bin,
        config_root=config_root,
        library_root=library_root,
        state_root=state_root,
        log_path=state_root / "auto-sync.log",
    )

    generated_dir = state_root / "generated"
    systemd_unit_path = generated_dir / "music-stack-auto-sync.service"
    udev_rule_path = generated_dir / "99-ipod-music-stack.rules"
    write_text_atomic(systemd_unit, systemd_unit_path)
    write_text_atomic(_UDEV_RULE_TEMPLATE, udev_rule_path)

    return {
        "systemd_unit": systemd_unit,
        "udev_rule": _UDEV_RULE_TEMPLATE,
        "install_commands": [
            f"sudo cp {systemd_unit_path} {_SYSTEMD_UNIT_INSTALL_PATH}",
            f"sudo cp {udev_rule_path} {_UDEV_RULE_INSTALL_PATH}",
            "sudo systemctl daemon-reload",
            "sudo udevadm control --reload-rules",
        ],
        "status": {
            "systemd_installed": _SYSTEMD_UNIT_INSTALL_PATH.is_file(),
            "udev_rule_installed": _UDEV_RULE_INSTALL_PATH.is_file(),
        },
    }
